### ISSUE TITLE
Cookies in nikto.conf are not being sent

### ISSUE THREAD

**Issue by amroot** [sullo/nikto#440]
Setting 'STATIC-COOKIE="name=value";"something=nothing"' in nikto.conf does not seem to include cookies in future requests. 

Nikto main: 2.1.6

![1_config](https://cloud.githubusercontent.com/assets/3596912/22515393/2961fb38-e857-11e6-80c4-e0809935ef7d.png)

![2_request](https://cloud.githubusercontent.com/assets/3596912/22515392/295eedda-e857-11e6-97e8-ede261411d35.png)

![3_request](https://cloud.githubusercontent.com/assets/3596912/22515391/295e0e06-e857-11e6-9f4c-36f936ad3c96.png)

**Comment by sullo** [comment]
Thanks for the detailed report. I may have missed checking in an update here as I did test (I swear!), but anyway it is fixed now. 

The first two requests that check for a port open and a proxy open *do not* use the cookies--that requires a bit of rework because of how it's done. I don't believe they are necessary as they are only checking that the connection works. If that becomes an issue the order of operations will have to be changed some more. 

I'll leave this open for now; if you can confirm it works for you & close I'd appreciate it.

**Comment by shengulong** [comment]
I come with the same thing,sovled? @sullo @amroot 
ths

**Comment by shengulong** [comment]
I get the solution by “git checkout 2.2.0”。 @sullo you should modify the master branch。
ths

**Comment by shengulong** [comment]
but,I can't get the result that i want.
in nikto.conf:STATIC-COOKIE="cookie1"="cookie value";"cookie2"="cookie val"
the result:
![default](https://cloud.githubusercontent.com/assets/9910148/22730069/66d0f680-ee20-11e6-830f-e8058a5f8395.png)
I don't want the double quotation marks

**Comment by shengulong** [comment]
so i suggest modify the nikto.conf like this : STATIC-COOKIE=cookie1=value1;cookie2=value2
and modify the nikto.pl one the 109 line like this :       if ($p =~ /([^=]+)=(.+)/) {

**Comment by sullo** [comment]
Cookies should have quotes around the whole name/value pair, like:
`"STATIC-COOKIE="cookie1=value1";"cookie2=value2"`

I'll check the change into the 2.1.x branch; sorry I thought I was on that!

**Comment by sullo** [comment]
Ok, my tests with the master & 2.2.0 branches show both working, and correct example SET-COOKIE values are in nikto.conf

**Comment by tautology0** [comment]
I'll just point out that you should be able to do this on the command line without touching nikto.conf, using the -O option, e.g.:

-O STATIC-COOKIE="fred=jim"
