### ISSUE TITLE
Can't find files used to generate reports' messages (for translation)

### ISSUE THREAD

**Issue by AmandaBSobrinho** [sullo/nikto#522]
I would like to generate reports in Brazilian Portuguese, but the only file I could find that has some of the messages on the reports is /usr/share/nikto/plugins/nikto_headers.plugin. 

However, there are some messages that appear in the reports but are not in this file.

So which files should I edit in order to produce a translated XML report?

**Comment by sullo** [comment]
That's a tall order, and not easy, unfortunately. The findings are in both
plugins (look for add_vulnerability) and all the files in the "databases"
directory.

The report templates are in the "templates" directory and those would be
easier to tackle as it would be the headers and other generic report
information. You could make a new HTML format and we could add it as a new
report type.

On Mar 5, 2018 1:59 PM, "Amanda Barbosa Sobrinho" <notifications@github.com>
wrote:

I would like to generate reports in Brazilian Portuguese, but the only file
I could find that has some of the messages on the reports is
/usr/share/nikto/plugins/nikto_headers.plugin.

However, there are some messages that appear in the reports but are not in
this file.

So which files should I edit in order to produce a translated XML report?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sullo/nikto/issues/522>, or mute the thread

**Comment by sullo** [comment]
Closing as "won't fix"
