### ISSUE TITLE
Error if HTTP Response is empty

### ISSUE THREAD

**Issue by leisipeisi** [sullo/nikto#529]
Hi everyone,

I am using nikto to probe a webserver which shows the behaviour to send empty HTTP Respones to some requests but still sets the content length to some value greater than zero. For example:

```
HTTP/1.1 200 OK
Date: Wed, 24 Mar 1993 21:39:22 GMT
Server: XXXX
Connection: close
Content-Length: 7680
Last-Modified: Wed, 24 Mar 1993 21:39:22 GMT
Cache-Control: max-age=3600, private
Accept-Ranges = none
```

nikto counts this response as an error and stops after 20 of these responses. I see that this is not a normal behaviour, but I would expect this response to be logged as "unexpected response" or something, but not as an error.

What is your opinion on this? Is the classification of this response as error done on purpose or just a side product? Do you think it would make sense to classify it in an other way?

Additional question: Is it possible to set the error limit up from the command line? That would be not the best way, but a workaround for me since I am not able to scan the whole webserver due to the error limit of 20.

Thank you!

**Comment by sullo** [comment]
Apologies as I don't recall seeing this issue ever. In case this crops up again for you or anyone, there are a few things:

- The failure condition is determined in LibWhisker, which is likely because there is an empty body but a non-zero content length. I don't think this warrants a change given that it's a small edge case.
- You can change the FAILURES value in nikto.conf (rename nikto.conf.default) to some large number (it's 20 by default).
