### ISSUE TITLE
Try to scan dvwa but cookie settings failed 

### ISSUE THREAD

**Issue by EXHades** [sullo/nikto#586]
my sure that  have set the cookie but he did not send it.
my using the master branches 
![image](https://user-images.githubusercontent.com/22260242/53383436-a5322680-39b2-11e9-8137-cab6b69643c4.png)
![image](https://user-images.githubusercontent.com/22260242/53383416-89c71b80-39b2-11e9-8940-8cfa5f0ab5b8.png)

**Comment by EXHades** [comment]
I tried using -0 
but
![image](https://user-images.githubusercontent.com/22260242/53385093-38218f80-39b8-11e9-903c-38d40d507c3b.png)
![image](https://user-images.githubusercontent.com/22260242/53385104-3f489d80-39b8-11e9-9f02-ddd3e16b824d.png)

**Comment by EXHades** [comment]
![image](https://user-images.githubusercontent.com/22260242/53385615-f2fe5d00-39b9-11e9-94a0-b9bf46e529b4.png)
![image](https://user-images.githubusercontent.com/22260242/53385656-1a552a00-39ba-11e9-8680-1df4baf19829.png)

**Comment by digininja** [comment]
Works fine for me with the latest master. This was the command I used:

```
$ ./program/nikto.pl  -host dvwa.test -useproxy
```

![image](https://user-images.githubusercontent.com/117081/53400954-c55be880-39a6-11e9-8788-f0b6d5fdaea5.png)

![image](https://user-images.githubusercontent.com/117081/53400965-cbea6000-39a6-11e9-9cf1-a7ffa5965bc0.png)

**Comment by digininja** [comment]
It isn't working from the command line though. Not exactly sure where the quotes and ='s go either, is this right?

```
$ ./program/nikto.pl  -host dvwa.test -useproxy -Option STATIC-COOKIE="hello=world"
```

**Comment by EXHades** [comment]
ok ,I restarted the system, nikto.config Working normally.
![image](https://user-images.githubusercontent.com/22260242/53460116-fb689d80-3a76-11e9-8e06-934d575b6387.png)
![image](https://user-images.githubusercontent.com/22260242/53460106-f3106280-3a76-11e9-8379-c5a0ee608920.png)

but use `-Option`  sent cookie failed
```
$ ./program/nikto.pl  -host 192.168.0.171:8888 -Option STATIC-COOKIE="PHPSESSID=phi5sskquc4rkud00qdfmvc6p5;security=low" -useproxy
```
![image](https://user-images.githubusercontent.com/22260242/53460467-2d2e3400-3a78-11e9-8ca9-7098122c975b.png)

**Comment by tautology0** [comment]
Looking at the parsing in the code for -Option, the = will mess it up as it uses the perl split method on an '=' sign, which means that STATIC-COOKIE with end up set to PHPSESSID.

That should teach me to just add an option without full testing it...

**Comment by digininja** [comment]
I thought there might be some odd parsing going on with the extra = and " in there. Happy to test anything if you need it.

**Comment by tautology0** [comment]
Nope that's a false positive - it does parse it correctly. What messes up is where Nikto puts the cookies from STATIC-COOKIE into the cookiejar.

Nikto parses the contents of STATIC-COOKIE with the following rules:
- cookies are separately by a ;
- a cookie is surrounded by quotes "

These are hostile characters in a *nix shell, so the the easy solution is to wrap them in single quotes:
`-O 'STATIC-COOKIE="bob=123";"jim=fred"'`

To fix this would require a change. To my thinking, the "'s are superfluous, but I'd like Sullo to rule on this one.

**Comment by sullo** [comment]
RFC-6265 really only calls out ; and = as special characters for parsing, and at that get a bit complicated in the processing rules (more than I would have thought)--most of which we can ignore because we may want to set abnormal values.

I'm not sure I see a problem with encasing it all in ' to avoid shell interpreting and acting on characters.  The only reason we need the " is to allow for multiple cookies, e.g.

`-O 'STATIC-COOKIE="mycookie=monster; security=laughable; path=/app;""mycookie2=junk"'
`

(technically don't need a delineator between the two cookies, but it sure looks ugly.)

This would let us:

1. operate on `STATIC-COOKIE` alone from any other -O strings (_can we support -O more than once? that'd help_)

2. Split the part post `STATIC-COOKIE=` on `"` to be the actual cookie name/value pairs to set

3. Decode any encoded strings in the name/value pairs (ideally just value)

3. Set cookies (`mycookie2=junk`)

**What am I not thinking of?**

Footnote: to add a ; to a cookie value/param it would have to be encoded like %x3B so we need to _not_ decode. If the server receives `Set-Cookie: cookie=some%x3B123` it can or may handle it, but if we shouldn't turn that into `Set-Cookie: cookie=some; 123` before it gets there.

**Comment by digininja** [comment]
I would prefer to see:

`-O 'STATIC-COOKIE="mycookie=monster; security=laughable; path=/app; mycookie2=junk'`

as it means you can take the cookie line directly out of a HTTP request.

Would it break too much to change it so you have:

`-O "cookie: mycookie=monster; security=laughable; path=/app; mycookie2=junk"`

Then it would become a header rather than an option and would let you add extra things like bearer tokens for authentication or referrer headers.

**Comment by digininja** [comment]
and I agree with your footnote, don't decode what is provided.

**Comment by sullo** [comment]
well we could also make it possible to do headers on the cli as something distinct from -O. 

@digininja wouldn't your second string (set a header) break because `mycookie2=junk` would actually be part of `mycookie` since there's only one "cookie:" bit?  It should be:

`-O "cookie: mycookie=monster; security=laughable; path=/app; cookie: mycookie2=junk"`

I think.

So two proposals here:

1. accept -O STATIC-COOKIE with goal of avoiding shell interpretation AND matching the .conf format (if possible)

2. Explicitly allow any header to be set from the command line.

I'm ok with both but not sure when I'll have time for the latter soon, unless someone else can write it.

**Comment by digininja** [comment]
1. That line is directly from a HTTP header so you wouldn't need to parse it, you would just throw it straight in as a header.

What about not letting them be combined?

```
-O "STATIC-COOKIE: mycookie=monster" -O "STATIC-COOKIE: security=blah"
```

Would that be easier to parse?

2. Yes, a headers line would be good, not sure I've ever needed it though so no rush on my part.
