### ISSUE TITLE
Enhancement: Ignore or unify required case of arguments

### ISSUE THREAD

**Issue by Hundifan33** [sullo/nikto#619]
For example currently -update start with an lowercase character while -Version uses an uppercase letter, which is really unintuitive. So I propose either ignoring the case of the first character so you can also for example use -version or making everything upper or lowercase.

**Comment by sullo** [comment]
There are currently several options which do this by design, so that there can be both -Version and -vhost with the lowercase option generally being the more common one. 

I appreciate the feedback but at this point in the program life it's not something I'd want to invest the time into, as there are a lot of cascading changes and other programs which may pass CLI arguments to Nikto.
