### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by Jeeppler** [sullo/nikto#654]
According to the [documentation](https://cirt.net/nikto2-docs/licences.html) nikto is published under a GPL license. There is no explanation regarding the specific GPL license version (v2 or v3).

It would be nice put the license information more prominently into the source code with the full text of the license.

**Comment by pombredanne** [comment]
@Jeeppler @sullo actually the text in https://github.com/sullo/nikto/blob/master/program/docs/LICENSE.txt is a truncated version of the GPL 2.0 ... it would be great to restore the original untruncated both for clarity and because truncating the GPL text is in itself a violation of the [GPL ](https://www.gnu.org/licenses/old-licenses/gpl-2.0.html) as it starts with:

> Everyone is permitted to copy and distribute verbatim copies
of this license document, but changing it is not allowed.

**Comment by iasdeoupxe** [comment]
Seems there is already an open PR for this: https://github.com/sullo/nikto/pull/661

**Comment by sullo** [comment]
closing; resolved in #661
